Vagrant.configure("2") do |config|
  
  config.vm.define :pxeserver do |pxeserver|
    pxeserver.vm.box = "bento/centos-7.9"
    pxeserver.vm.network :private_network, ip: "192.168.20.3"
    pxeserver.vm.hostname = "pxeserver"
  end

end