# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.define :cliente do |cliente|
    #cliente.vm.box = "bento/centos-7.9"
    #cliente.vm.network :private_network, ip: "192.168.50.2"
    #cliente.vm.hostname = "cliente"
  #end
  
  config.vm.define :pxeserver do |pxeserver|
    pxeserver.vm.box = "bento/centos-7.9"
    pxeserver.vm.network :private_network, ip: "192.168.40.3"
    pxeserver.vm.hostname = "pxeserver"
  end

end